[srv_samba]
srv_samba ansible_host=3.85.223.9 ansible_user=ubuntu
[srv_arquivos]
srv_arquivos ansible_host=54.167.222.181 ansible_user=ubuntu
[srv_grafana]
srv_grafana ansible_host=32.192.198.191 ansible_user=ubuntu